name: renovate

on:
  workflow_dispatch:
    inputs:
      force-run:
        description: >-
          Force a run regardless of the schedule configuration.
        required: false
        default: false
        type: boolean
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    uses: lrstanley/.github/.github/workflows/renovate.yml@master
    secrets:
      app-id: ${{ secrets.BOT_APP_ID }}
      app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
